-- 2021년에 가입한 전체 회원에서 상품을 구매한 회원수, 상품을 구매한 회원의 비율 / 년/월

SELECT YEAR(O.SALES_DATE) AS YEAR, MONTH(O.SALES_DATE) AS MONTH, COUNT(DISTINCT U.USER_ID) AS PURCHASED_USERS, ROUND(COUNT(DISTINCT U.USER_ID)/C.COUNT, 1) AS PUCHASED_RATIO
FROM ONLINE_SALE O JOIN (SELECT USER_ID FROM USER_INFO WHERE JOINED BETWEEN '2021-01-01' AND '2021-12-31') U ON O.USER_ID = U.USER_ID, (SELECT COUNT(*) AS COUNT FROM USER_INFO WHERE JOINED BETWEEN '2021-01-01' AND '2021-12-31') C
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH;