-- 코드를 작성해주세요
SELECT E.EMP_NO, E.EMP_NAME, CASE 
    WHEN S.AVG_GRADE >= 96 THEN 'S'
    WHEN S.AVG_GRADE >= 90 THEN 'A'
    WHEN S.AVG_GRADE >= 80 THEN 'B'
    ELSE 'C' END AS GRADE,
    CASE
        WHEN S.AVG_GRADE >= 96 THEN E.SAL * 0.2
        WHEN S.AVG_GRADE >= 90 THEN E.SAL * 0.15
        WHEN S.AVG_GRADE >= 80 THEN E.SAL * 0.1
        ELSE 0 END AS BONUS
FROM HR_EMPLOYEES E JOIN
(SELECT EMP_NO, AVG(SCORE) AS AVG_GRADE FROM HR_GRADE
GROUP BY EMP_NO) S
ON E.EMP_NO = S.EMP_NO
ORDER BY E.EMP_NO;