-- 코드를 입력하세요
-- 보호 시작보다 입양일이 더 빠른 동물의 아이디와 이름을 조회
-- 보호시작일이 빠른 순으로 정렬
SELECT ANIMAL_INS.ANIMAL_ID, ANIMAL_INS.NAME
FROM ANIMAL_INS, ANIMAL_OUTS
WHERE ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID 
AND ANIMAL_INS.DATETIME > ANIMAL_OUTS.DATETIME 
ORDER BY ANIMAL_INS.DATETIME