-- 코드를 작성해주세요
SELECT YEAR(E.DIFFERENTIATION_DATE) AS YEAR, ABS(E.SIZE_OF_COLONY - D.MAX) AS YEAR_DEV, E.ID FROM ECOLI_DATA E JOIN
(SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX FROM ECOLI_DATA
GROUP BY YEAR) D ON D.YEAR = YEAR(E.DIFFERENTIATION_DATE)
ORDER BY YEAR, YEAR_DEV;