-- 잡은 BASS와 SNAPPER의 수를 출력
-- 컬럼명은 FISH_COUNT
SELECT COUNT(*) AS "FISH_COUNT"
FROM FISH_INFO, FISH_NAME_INFO 
WHERE (FISH_NAME_INFO.FISH_NAME = "BASS" OR FISH_NAME_INFO.FISH_NAME = "SNAPPER") 
AND FISH_NAME_INFO.FISH_TYPE = FISH_INFO.FISH_TYPE