-- 코드를 작성해주세요
SELECT M.ID, F.FISH_NAME, M.LENG AS LENGTH FROM FISH_NAME_INFO F JOIN (SELECT I.ID AS ID, I.FISH_TYPE AS TY, I.LENGTH AS LENG FROM FISH_INFO I JOIN (SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH FROM FISH_INFO
GROUP BY FISH_TYPE) J ON I.FISH_TYPE = J.FISH_TYPE
WHERE I.LENGTH = J.LENGTH) M
ON F.FISH_TYPE = M.TY
ORDER BY M.ID;

;